In [1]:
# !pip install librosa

In [1]:
import numpy as np
import librosa

In [2]:
path = 'C:\\Users\\saive\\.cache\\kagglehub\\datasets\\uwrfkaggler\\ravdess-emotional-speech-audio\\versions\\1'
path

'C:\\Users\\saive\\.cache\\kagglehub\\datasets\\uwrfkaggler\\ravdess-emotional-speech-audio\\versions\\1'

In [3]:
path

'C:\\Users\\saive\\.cache\\kagglehub\\datasets\\uwrfkaggler\\ravdess-emotional-speech-audio\\versions\\1'

In [4]:
import re
import os
import shutil

destination = "D:\\Emotion_Recognizer_using_transformers\\neutral"
subPaths = ["\\Actor_01", "\\Actor_02", "\\Actor_03", "\\Actor_04", "\\Actor_05", "\\Actor_06", "\\Actor_07", "\\Actor_08", "\\Actor_09", "\\Actor_10", "\\Actor_11", "\\Actor_12", "\\Actor_13", "\\Actor_14", "\\Actor_15", "\\Actor_16", "\\Actor_17", "\\Actor_18", "\\Actor_19", "\\Actor_20"]
initPath = path

for i in range(len(subPaths)):
    path += subPaths[i]
    for file in os.listdir(path):
        filePath = os.path.join(path, file)
        neutral = re.search(r'\d{2}-\d{2}-01-\d{2}-\d{2}-\d{2}-\d{2}', filePath)

        if neutral and os.path.isfile(filePath):
            destination_path = os.path.join(destination, file)
            shutil.copyfile(filePath, destination_path)
            print("Copied file:", file)
    
    path = initPath

path = initPath


Copied file: 03-01-01-01-01-01-01.wav
Copied file: 03-01-01-01-01-02-01.wav
Copied file: 03-01-01-01-02-01-01.wav
Copied file: 03-01-01-01-02-02-01.wav
Copied file: 03-01-01-01-01-01-02.wav
Copied file: 03-01-01-01-01-02-02.wav
Copied file: 03-01-01-01-02-01-02.wav
Copied file: 03-01-01-01-02-02-02.wav
Copied file: 03-01-01-01-01-01-03.wav
Copied file: 03-01-01-01-01-02-03.wav
Copied file: 03-01-01-01-02-01-03.wav
Copied file: 03-01-01-01-02-02-03.wav
Copied file: 03-01-01-01-01-01-04.wav
Copied file: 03-01-01-01-01-02-04.wav
Copied file: 03-01-01-01-02-01-04.wav
Copied file: 03-01-01-01-02-02-04.wav
Copied file: 03-01-01-01-01-01-05.wav
Copied file: 03-01-01-01-01-02-05.wav
Copied file: 03-01-01-01-02-01-05.wav
Copied file: 03-01-01-01-02-02-05.wav
Copied file: 03-01-01-01-01-01-06.wav
Copied file: 03-01-01-01-01-02-06.wav
Copied file: 03-01-01-01-02-01-06.wav
Copied file: 03-01-01-01-02-02-06.wav
Copied file: 03-01-01-01-01-01-07.wav
Copied file: 03-01-01-01-01-02-07.wav
Copied file:

In [5]:
import re
import os
import shutil

destination = "D:\\Emotion_Recognizer_using_transformers\\angry"
subPaths = ["\\Actor_01", "\\Actor_02", "\\Actor_03", "\\Actor_04", "\\Actor_05", "\\Actor_06", "\\Actor_07", "\\Actor_08", "\\Actor_09", "\\Actor_10"]
initPath = path

for i in range(len(subPaths)):
    path += subPaths[i]
    for file in os.listdir(path):
        filePath = os.path.join(path, file)
        neutral = re.search(r'\d{2}-\d{2}-05-\d{2}-\d{2}-\d{2}-\d{2}', filePath)

        if neutral and os.path.isfile(filePath):
            shutil.copyfile(filePath, destination_path)
            destination_path = os.path.join(destination, file)
            print("Copied file:", file)
    
    path = initPath

Copied file: 03-01-05-01-01-01-01.wav
Copied file: 03-01-05-01-01-02-01.wav
Copied file: 03-01-05-01-02-01-01.wav
Copied file: 03-01-05-01-02-02-01.wav
Copied file: 03-01-05-02-01-01-01.wav
Copied file: 03-01-05-02-01-02-01.wav
Copied file: 03-01-05-02-02-01-01.wav
Copied file: 03-01-05-02-02-02-01.wav
Copied file: 03-01-05-01-01-01-02.wav
Copied file: 03-01-05-01-01-02-02.wav
Copied file: 03-01-05-01-02-01-02.wav
Copied file: 03-01-05-01-02-02-02.wav
Copied file: 03-01-05-02-01-01-02.wav
Copied file: 03-01-05-02-01-02-02.wav
Copied file: 03-01-05-02-02-01-02.wav
Copied file: 03-01-05-02-02-02-02.wav
Copied file: 03-01-05-01-01-01-03.wav
Copied file: 03-01-05-01-01-02-03.wav
Copied file: 03-01-05-01-02-01-03.wav
Copied file: 03-01-05-01-02-02-03.wav
Copied file: 03-01-05-02-01-01-03.wav
Copied file: 03-01-05-02-01-02-03.wav
Copied file: 03-01-05-02-02-01-03.wav
Copied file: 03-01-05-02-02-02-03.wav
Copied file: 03-01-05-01-01-01-04.wav
Copied file: 03-01-05-01-01-02-04.wav
Copied file:

In [6]:
import re
import os
import shutil

destination = "D:\\Emotion_Recognizer_using_transformers\\sad"
subPaths = ["\\Actor_01", "\\Actor_02", "\\Actor_03", "\\Actor_04", "\\Actor_05", "\\Actor_06", "\\Actor_07", "\\Actor_08", "\\Actor_09", "\\Actor_10"]
initPath = path

for i in range(len(subPaths)):
    path += subPaths[i]
    for file in os.listdir(path):
        filePath = os.path.join(path, file)
        neutral = re.search(r'\d{2}-\d{2}-04-\d{2}-\d{2}-\d{2}-\d{2}', filePath)

        if neutral and os.path.isfile(filePath):
            destination_path = os.path.join(destination, file)
            shutil.copyfile(filePath, destination_path)
            print("Copied file:", file)
    
    path = initPath

Copied file: 03-01-04-01-01-01-01.wav


Copied file: 03-01-04-01-01-02-01.wav
Copied file: 03-01-04-01-02-01-01.wav
Copied file: 03-01-04-01-02-02-01.wav
Copied file: 03-01-04-02-01-01-01.wav
Copied file: 03-01-04-02-01-02-01.wav
Copied file: 03-01-04-02-02-01-01.wav
Copied file: 03-01-04-02-02-02-01.wav
Copied file: 03-01-04-01-01-01-02.wav
Copied file: 03-01-04-01-01-02-02.wav
Copied file: 03-01-04-01-02-01-02.wav
Copied file: 03-01-04-01-02-02-02.wav
Copied file: 03-01-04-02-01-01-02.wav
Copied file: 03-01-04-02-01-02-02.wav
Copied file: 03-01-04-02-02-01-02.wav
Copied file: 03-01-04-02-02-02-02.wav
Copied file: 03-01-04-01-01-01-03.wav
Copied file: 03-01-04-01-01-02-03.wav
Copied file: 03-01-04-01-02-01-03.wav
Copied file: 03-01-04-01-02-02-03.wav
Copied file: 03-01-04-02-01-01-03.wav
Copied file: 03-01-04-02-01-02-03.wav
Copied file: 03-01-04-02-02-01-03.wav
Copied file: 03-01-04-02-02-02-03.wav
Copied file: 03-01-04-01-01-01-04.wav
Copied file: 03-01-04-01-01-02-04.wav
Copied file: 03-01-04-01-02-01-04.wav
Copied file:

In [7]:
import re
import os
import shutil

destination = "D:\\Emotion_Recognizer_using_transformers\\happy"
subPaths = ["\\Actor_01", "\\Actor_02", "\\Actor_03", "\\Actor_04", "\\Actor_05", "\\Actor_06", "\\Actor_07", "\\Actor_08", "\\Actor_09", "\\Actor_10"]
initPath = path

for i in range(len(subPaths)):
    path += subPaths[i]
    for file in os.listdir(path):
        filePath = os.path.join(path, file)
        neutral = re.search(r'\d{2}-\d{2}-03-\d{2}-\d{2}-\d{2}-\d{2}', filePath)

        if neutral and os.path.isfile(filePath):
            shutil.copyfile(filePath, destination_path)
            destination_path = os.path.join(destination, file)
            print("Copied file:", file)
    
    path = initPath

Copied file: 03-01-03-01-01-01-01.wav
Copied file: 03-01-03-01-01-02-01.wav
Copied file: 03-01-03-01-02-01-01.wav
Copied file: 03-01-03-01-02-02-01.wav
Copied file: 03-01-03-02-01-01-01.wav
Copied file: 03-01-03-02-01-02-01.wav
Copied file: 03-01-03-02-02-01-01.wav
Copied file: 03-01-03-02-02-02-01.wav
Copied file: 03-01-03-01-01-01-02.wav
Copied file: 03-01-03-01-01-02-02.wav
Copied file: 03-01-03-01-02-01-02.wav
Copied file: 03-01-03-01-02-02-02.wav
Copied file: 03-01-03-02-01-01-02.wav
Copied file: 03-01-03-02-01-02-02.wav
Copied file: 03-01-03-02-02-01-02.wav
Copied file: 03-01-03-02-02-02-02.wav
Copied file: 03-01-03-01-01-01-03.wav
Copied file: 03-01-03-01-01-02-03.wav
Copied file: 03-01-03-01-02-01-03.wav
Copied file: 03-01-03-01-02-02-03.wav
Copied file: 03-01-03-02-01-01-03.wav
Copied file: 03-01-03-02-01-02-03.wav
Copied file: 03-01-03-02-02-01-03.wav
Copied file: 03-01-03-02-02-02-03.wav
Copied file: 03-01-03-01-01-01-04.wav
Copied file: 03-01-03-01-01-02-04.wav
Copied file:

In [8]:
neutral = []
sad = []
angry = []
happy=[]
y=[]

In [ ]:
import os
source = "D:\\Emotion_Recognizer_using_transformers\\neutral"

for file in os.listdir(source):
    # var, sr = librosa.load(source + "\\" + file)
    # neutral.append(var)
    neutral.append(librosa.load(source + "\\" + file, sr=None))
    y.append('neutral')

In [10]:
source = "D:\\Emotion_Recognizer_using_transformers\\sad"

for file in os.listdir(source):
    # sad.append(librosa.tone(source + "\\" + file, sr=48000))
    # var, sr = librosa.load(source + "\\" + file, sr=22050, duration=2)
    # sad.append(librosa.tone(var, duration=2, sr=22050))
    
    # var, sr = librosa.load(source + "\\" + file)
    # sad.append(var)
    sad.append(librosa.load(source + "\\" + file, sr=None))
    y.append('sad')

In [11]:
source = "D:\\Emotion_Recognizer_using_transformers\\angry"

for file in os.listdir(source):
    # angry.append(librosa.tone(source + "\\" + file, sr=48000))
    # var, sr = librosa.load(source + "\\" + file, sr=22050, duration=2)
    # angry.append(librosa.tone(var, duration=2, sr=22050))

    
    # var, sr = librosa.load(source + "\\" + file)
    # angry.append(var)
    angry.append(librosa.load(source + "\\" + file, sr=None))
    y.append('angry')

In [12]:
import os
source = "D:\\Emotion_Recognizer_using_transformers\\happy"

for file in os.listdir(source):
    # happy.append(librosa.tone(source + "\\" + file, sr=48000))
    # var, sr = librosa.load(source + "\\" + file, sr=22050, duration=2)
    # happy.append(librosa.tone(var, duration=2, sr=22050))

    
    # var, sr = librosa.load(source + "\\" + file, sr=None)
    # happy.append(var)
    happy.append(librosa.load(source + "\\" + file, sr=None))
    y.append('happy')

In [13]:
len(neutral)

80

In [14]:
len(angry)

79

In [15]:
len(sad)

80

In [16]:
len(happy)

80

In [17]:
x = []
for i in neutral:
    x.append(i[0])
for i in angry:
    x.append(i[0])
for i in sad:
    x.append(i[0])
for i in happy:
    x.append(i[0])

In [18]:
len(x)

319

In [19]:
y

['neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'neutral',
 'sad',
 'sad',
 'sad',
 'sad',
 'sad',


In [20]:
type(x[0])

numpy.ndarray

In [21]:
# x = x[0]
# for i in range(len(x)):
x[1]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [22]:
print(len(x))

319


In [23]:
for i in x:
    print(i.shape)

(158558,)
(174574,)
(164965,)
(158558,)
(172973,)
(160160,)
(187388,)
(168168,)
(156957,)
(169770,)
(150551,)
(174574,)
(152152,)
(166566,)
(161762,)
(179379,)
(184184,)
(166567,)
(161762,)
(166566,)
(160160,)
(172973,)
(168168,)
(161762,)
(174575,)
(172973,)
(182583,)
(174575,)
(153754,)
(184184,)
(148949,)
(169770,)
(153753,)
(160160,)
(164965,)
(179380,)
(168168,)
(169770,)
(155355,)
(171371,)
(156956,)
(180980,)
(168168,)
(156957,)
(148948,)
(163363,)
(198598,)
(169769,)
(160160,)
(179379,)
(153754,)
(172973,)
(147347,)
(166567,)
(164964,)
(172973,)
(168168,)
(166566,)
(160160,)
(164965,)
(152152,)
(172972,)
(166567,)
(155355,)
(172973,)
(164965,)
(179379,)
(168168,)
(155356,)
(176176,)
(152152,)
(174575,)
(150550,)
(171371,)
(163363,)
(171371,)
(166566,)
(166567,)
(158558,)
(185786,)
(188989,)
(176176,)
(195395,)
(172973,)
(182582,)
(190590,)
(190591,)
(172973,)
(171372,)
(192192,)
(168168,)
(180980,)
(182583,)
(166566,)
(195395,)
(201801,)
(192192,)
(169770,)
(179379,)
(196997,)


In [24]:
# import sys
# ans = sys.maxsize
# for i in x:
#     ans = min(len(i), ans)

# ans

avg_size = int(np.mean([arr.shape[0] for arr in x]))


In [25]:
avg_size

176532

In [26]:
# for i in range(0, len(x)):
#     x[i] = x[i][:ans]

padded_x = []
for arr in x:
    if arr.shape[0] > avg_size:
        arr = arr[:avg_size]
    # Ensure consistent padding calculation
    if len(arr.shape) == 1:  # If array is 1D
        pad_width = (0, max(0, avg_size - len(arr)))  # Pad to the right
        padded_x.append(np.pad(arr, pad_width, mode='constant'))
    else:
        raise ValueError("Input arrays are not uniformly 1D. Check dimensions!")

# Step 3: Convert to a NumPy array (now safe)
for i in padded_x:
    print(i.shape)
# padded_x = np.array(padded_x)


(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)
(176532,)


In [27]:
x = padded_x

In [ ]:
for i in range(len(y)):
    if y[i] == 'neutral':
        y[i] = 0
    if y[i] == 'angry':
        y[i] = 1
    if y[i] == 'sad':
        y[i] = 2
    if y[i] == 'happy':
        y[i] = 3

In [29]:
y

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,


In [30]:
y = np.array(y)

In [31]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [33]:
x_train = np.array(x_train)
x_test = np.array(x_test)

In [34]:
type(x_train)

numpy.ndarray

In [35]:
type(y_train)

numpy.ndarray

In [36]:
type(y_train)

numpy.ndarray

In [37]:
# x_train = x_train.reshape(-1, 1)
# x_test = x_test.reshape(-1, 1)

In [38]:
y_train

array([3, 2, 1, 1, 0, 0, 2, 0, 1, 1, 3, 2, 0, 2, 3, 2, 1, 1, 3, 1, 2, 1,
       2, 0, 3, 3, 2, 3, 0, 2, 0, 0, 3, 3, 1, 2, 3, 0, 1, 3, 0, 0, 1, 3,
       2, 2, 3, 1, 3, 1, 2, 2, 0, 2, 0, 2, 1, 1, 1, 2, 1, 3, 3, 0, 2, 2,
       1, 2, 1, 3, 0, 1, 0, 0, 1, 3, 3, 2, 1, 2, 3, 2, 2, 3, 2, 0, 0, 2,
       1, 1, 2, 0, 2, 1, 0, 0, 2, 1, 1, 1, 3, 0, 1, 0, 2, 1, 0, 3, 2, 0,
       0, 0, 3, 1, 1, 0, 3, 3, 1, 3, 2, 0, 0, 0, 2, 1, 2, 0, 3, 0, 0, 0,
       2, 0, 3, 3, 3, 3, 2, 1, 0, 1, 3, 2, 1, 3, 1, 3, 0, 2, 2, 1, 3, 1,
       2, 2, 1, 3, 2, 3, 2, 3, 1, 0, 1, 2, 0, 2, 3, 2, 3, 3, 1, 0, 0, 0,
       2, 3, 2, 1, 0, 1, 1, 2, 2, 0, 1, 1, 2, 1, 2, 3, 3, 3, 1, 2, 2, 3,
       3, 2, 2, 2, 0, 3, 3, 0, 2, 3, 0, 0, 3, 2, 0, 1, 1, 2, 3, 1, 0, 0,
       2, 1, 3, 3, 2, 3, 3, 1, 2, 1, 3, 2, 3, 0, 0, 1, 3, 1, 3, 0, 1, 2,
       0, 2, 3, 3, 3, 1, 0, 1, 3, 1, 2, 0, 1])

In [305]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(max_depth=10).fit(x_train, y_train)

In [306]:
y_pred = rfc.predict(x_test)

In [307]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.46875


In [308]:
print(accuracy_score(y_train, rfc.predict(x_train)))

0.996078431372549


In [309]:
from sklearn.svm import SVC

svc = SVC().fit(x_train, y_train)

In [310]:
new_y_pred = svc.predict(x_test)

In [311]:
print(accuracy_score(y_test, new_y_pred))

0.375


In [312]:
print(accuracy_score(y_train, svc.predict(x_train)))

0.5137254901960784


In [313]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

lr.fit(x_train, y_train)

LogisticRegression()

In [314]:
y_pred_LR = lr.predict(x_test)
accuracy_score(y_test, y_pred_LR)

0.265625

In [315]:
print(accuracy_score(y_train, lr.predict(x_train)))

0.9882352941176471


In [316]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB()

In [317]:
gnb_y_pred = gnb.predict(x_test)

In [318]:
accuracy_score(y_test, gnb_y_pred)

0.484375

In [319]:
print(accuracy_score(y_train, gnb.predict(x_train)))

0.5529411764705883


In [39]:
for i in x:
    print(i, "\n\n")

[0. 0. 0. ... 0. 0. 0.] 


[0. 0. 0. ... 0. 0. 0.] 


[-3.0517578e-05  0.0000000e+00 -3.0517578e-05 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00] 


[0. 0. 0. ... 0. 0. 0.] 


[0. 0. 0. ... 0. 0. 0.] 


[0. 0. 0. ... 0. 0. 0.] 


[ 6.1035156e-05 -6.1035156e-05 -6.1035156e-05 ...  6.1035156e-05
  9.1552734e-05  9.1552734e-05] 


[-0.00012207 -0.00018311 -0.00015259 ...  0.          0.
  0.        ] 


[0.00088501 0.00085449 0.00085449 ... 0.         0.         0.        ] 


[6.1035156e-05 3.0517578e-05 6.1035156e-05 ... 0.0000000e+00 0.0000000e+00
 0.0000000e+00] 


[0. 0. 0. ... 0. 0. 0.] 


[0. 0. 0. ... 0. 0. 0.] 


[-3.0517578e-05 -3.0517578e-05 -3.0517578e-05 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00] 


[0. 0. 0. ... 0. 0. 0.] 


[0. 0. 0. ... 0. 0. 0.] 


[0. 0. 0. ... 0. 0. 0.] 


[3.0517578e-04 3.0517578e-04 3.0517578e-04 ... 9.1552734e-05 9.1552734e-05
 1.2207031e-04] 


[0. 0. 0. ... 0. 0. 0.] 


[0. 0. 0. ... 0. 0. 0.] 


[0. 0. 0. ... 0. 0. 0.] 


[ 0.0000000e

In [40]:
import numpy as np

new_x = np.vstack(x_train)

In [41]:
new_x
m, n = new_x.shape

In [42]:
new_x = new_x.T

In [47]:
len(new_x[0])
import sys

In [48]:
(new_x)

array([[ 0.0000000e+00,  3.6621094e-04, -9.1552734e-05, ...,
         1.8310547e-04, -3.0517578e-05,  0.0000000e+00],
       [ 0.0000000e+00,  3.3569336e-04, -9.1552734e-05, ...,
         1.8310547e-04, -3.0517578e-05,  0.0000000e+00],
       [ 0.0000000e+00,  2.7465820e-04, -3.0517578e-05, ...,
         1.5258789e-04, -3.0517578e-05,  0.0000000e+00],
       ...,
       [ 0.0000000e+00, -6.1035156e-05,  2.1972656e-03, ...,
        -2.5329590e-03,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -3.3569336e-04,  2.2583008e-03, ...,
        -2.9602051e-03,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.2207031e-04,  2.1972656e-03, ...,
        -3.4790039e-03,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [ ]:
max_val = -sys.maxsize - 1

for i in new_x:
    for j in i:
        max_val = max(max_val, abs(j))

max_val

0.9991455

In [50]:
for i in range(len(new_x)):
    for j in range(len(new_x[i])):
        new_x[i][j] = new_x[i][j] / max_val


In [51]:
y = y_train.T

In [52]:
new_x

array([[ 0.0000000e+00,  3.6652412e-04, -9.1631031e-05, ...,
         1.8326206e-04, -3.0543677e-05,  0.0000000e+00],
       [ 0.0000000e+00,  3.3598044e-04, -9.1631031e-05, ...,
         1.8326206e-04, -3.0543677e-05,  0.0000000e+00],
       [ 0.0000000e+00,  2.7489310e-04, -3.0543677e-05, ...,
         1.5271839e-04, -3.0543677e-05,  0.0000000e+00],
       ...,
       [ 0.0000000e+00, -6.1087354e-05,  2.1991448e-03, ...,
        -2.5351252e-03,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -3.3598044e-04,  2.2602321e-03, ...,
        -2.9627366e-03,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.2217471e-04,  2.1991448e-03, ...,
        -3.4819792e-03,  0.0000000e+00,  0.0000000e+00]], dtype=float32)

In [53]:
# new_x = new_x[0]

In [54]:
new_x.shape

(176532, 255)

In [55]:
def init():
    W1 = np.random.rand(4, 176532) - 0.5
    b1 = np.random.rand(4, 255) - 0.5
    W2 = np.random.rand(4, 4) - 0.5
    b2 = np.random.rand(4, 255) - 0.5

    return W1, b1, W2, b2

In [56]:
def ReLu(X):
    return np.maximum(X, 0)

def softmax(X):
    X_shifted = X - np.max(X, axis=0, keepdims=True)  # Shift for numerical stability
    exp_X = np.exp(X_shifted)
    return exp_X / np.sum(exp_X, axis=0, keepdims=True)

In [57]:
def forward_propogation(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLu(Z1)

    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)

    return Z1, A1, Z2, A2

In [58]:
def One_Hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    return one_hot_Y.T

In [59]:
def deri_reLu(X):
    return X > 0

In [60]:
def backward_propogation(Z1, Y, A1, A2, W2, X):
    one_hot_Y = One_Hot(Y)

    dZ2 = A2 - one_hot_Y
    dW2 = 1/ m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)

    dZ1 = W2.T.dot(dZ2) * deri_reLu(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)

    return db1, db2, dW1, dW2

In [61]:
def update_params(db1, db2, dW1, dW2, W1, W2, b1, b2, alpha):
    W1 = W1 - dW1 * alpha
    W2 = W2 - dW2 * alpha
    
    b1 = b1 - db1 * alpha
    b2 = b2 - db2 * alpha

    return W1, W2, b1, b2

In [62]:
def getPredictions(A2):
    return np.argmax(A2, 0)

def getAccuracy(predictions, Y):
    return np.sum(predictions == Y) / Y.size

In [63]:
def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init()

    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_propogation(W1, b1, W2, b2, X)
        
        db1, db2, dW1, dW2 = backward_propogation(Z1, Y, A1, A2, W2, X)

        W1, W2, b1, b2 = update_params(db1, db2, dW1, dW2, W1, W2, b1, b2, alpha)

        if(i % 10 == 0):
            print(f"Iteration: {i}\t Accuracy = {getAccuracy(getPredictions(A2), Y)}")

    
    return W1, b1, W2, b2, A2

In [64]:
W1, b1, W2, b2, A2 = gradient_descent(new_x, y, 1000, 1)

Iteration: 0	 Accuracy = 0.2627450980392157
Iteration: 10	 Accuracy = 0.36470588235294116
Iteration: 20	 Accuracy = 0.396078431372549
Iteration: 30	 Accuracy = 0.43137254901960786
Iteration: 40	 Accuracy = 0.4627450980392157
Iteration: 50	 Accuracy = 0.4588235294117647
Iteration: 60	 Accuracy = 0.4666666666666667
Iteration: 70	 Accuracy = 0.47058823529411764
Iteration: 80	 Accuracy = 0.47058823529411764
Iteration: 90	 Accuracy = 0.47843137254901963
Iteration: 100	 Accuracy = 0.49019607843137253
Iteration: 110	 Accuracy = 0.4980392156862745
Iteration: 120	 Accuracy = 0.4980392156862745
Iteration: 130	 Accuracy = 0.5058823529411764
Iteration: 140	 Accuracy = 0.5058823529411764
Iteration: 150	 Accuracy = 0.5058823529411764
Iteration: 160	 Accuracy = 0.5137254901960784
Iteration: 170	 Accuracy = 0.5098039215686274
Iteration: 180	 Accuracy = 0.5215686274509804
Iteration: 190	 Accuracy = 0.5294117647058824
Iteration: 200	 Accuracy = 0.5372549019607843
Iteration: 210	 Accuracy = 0.53333333333

In [65]:
print(W1)
np.savetxt('w1.txt', W1)
np.savetxt('b1.txt', b1)
np.savetxt('w2.txt', W2)
np.savetxt('b2.txt', b2)

[[ 0.05896631 -0.44324358  0.4749907  ... -0.34873992  0.36956215
   0.45808957]
 [-0.06911976  0.4382454  -0.07186769 ...  0.0676453   0.00176942
  -0.36141782]
 [-0.3294501   0.3056101  -0.18424473 ...  0.13336889 -0.25991687
   0.15031005]
 [-0.20362246 -0.08316032  0.48140325 ... -0.27821061  0.26770187
  -0.14741976]]


In [66]:
W1 = np.loadtxt('w1.txt')
b1 = np.loadtxt('b1.txt')
W2 = np.loadtxt('w2.txt')
b2 = np.loadtxt('b2.txt')

In [67]:
count = 0
def make_predictions(X, W1, b1, W2, b2):
    _, _, _, A2 = forward_propogation(W1, b1, W2, b2, X)
    predictions = getPredictions(A2)
    return predictions

def test_prediction(index, W1, b1, W2, b2):
    global count
    # current_image = x_test[:, index, None]
    prediction = make_predictions(x_test[:, index, None], W1, b1, W2, b2)
    label = y[index]
    ans = [0, 0, 0, 0]
    for i in prediction:
        ans[i]+=1
    print(ans)
    print("prediction: ", ans.index(max(ans)))
    print("Label: ", label)
    if(label == ans.index(max(ans))):
        count += 1

In [68]:
new_x.shape

(176532, 255)

In [69]:
x_test.shape

(64, 176532)

In [70]:
new_x[0]

array([ 0.0000000e+00,  3.6652412e-04, -9.1631031e-05,  3.0543677e-05,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  3.0543677e-05,  0.0000000e+00,  1.5271839e-04,
        0.0000000e+00,  0.0000000e+00,  6.1087354e-05,  1.2217471e-04,
        0.0000000e+00,  9.1631031e-05,  0.0000000e+00,  0.0000000e+00,
       -6.7196088e-04,  0.0000000e+00,  0.0000000e+00,  0.0000000e+00,
        3.0543677e-05,  0.0000000e+00, -6.1087357e-04,  2.1380575e-04,
        3.0543677e-05, -9.1631031e-05,  0.0000000e+00,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -3.0543677e-05,
        3.0543677e-05,  1.2217471e-04,  0.0000000e+00, -9.1631031e-05,
        0.0000000e+00,  0.0000000e+00, -3.0543677e-05,  0.0000000e+00,
        0.0000000e+00,  9.1631031e-05,  3.0543677e-05,  0.0000000e+00,
        0.0000000e+00,  0.0000000e+00,  0.0000000e+00, -6.1087354e-05,
        0.0000000e+00, -9.1631031e-05, -9.1631031e-05,  0.0000000e+00,
      

In [71]:
maxx = 0
for i in range(len(x_test)):
    for j in range(len(x_test[i])):
        if(maxx < abs(x_test[i][j])):
            maxx = abs(x_test[i][j])

In [72]:
max

<function max>

In [73]:
for i in range(len(x_test)):
    for j in range(len(x_test[i])):
        x_test[i][j] = x_test[i][j] / maxx

In [74]:
x_test = x_test.T

In [75]:
x_test.shape

(176532, 64)

In [76]:
for i in range(64):
    test_prediction(i, W1, b1, W2, b2)

[0, 0, 175, 80]
prediction:  2
Label:  3
[0, 8, 247, 0]
prediction:  2
Label:  2
[0, 90, 165, 0]
prediction:  2
Label:  1
[16, 205, 23, 11]
prediction:  1
Label:  1
[23, 20, 124, 88]
prediction:  2
Label:  0
[45, 38, 93, 79]
prediction:  2
Label:  0
[74, 38, 87, 56]
prediction:  2
Label:  2
[0, 255, 0, 0]
prediction:  1
Label:  0
[163, 20, 52, 20]
prediction:  0
Label:  1
[26, 25, 111, 93]
prediction:  2
Label:  1
[24, 17, 123, 91]
prediction:  2
Label:  3
[0, 0, 255, 0]
prediction:  2
Label:  2
[0, 0, 209, 46]
prediction:  2
Label:  0
[37, 28, 85, 105]
prediction:  3
Label:  2
[9, 0, 17, 229]
prediction:  3
Label:  3
[0, 0, 138, 117]
prediction:  2
Label:  2
[0, 0, 0, 255]
prediction:  3
Label:  1
[0, 0, 255, 0]
prediction:  2
Label:  1
[27, 18, 77, 133]
prediction:  3
Label:  3
[33, 22, 89, 111]
prediction:  3
Label:  1
[2, 192, 61, 0]
prediction:  1
Label:  2
[3, 50, 172, 30]
prediction:  2
Label:  1
[0, 0, 255, 0]
prediction:  2
Label:  2
[3, 195, 51, 6]
prediction:  1
Label:  0
[0

In [77]:
test_accuracy = count / 64
print(test_accuracy)

0.3125
